### ISSUE TITLE
Failed to register...Try again

### ISSUE THREAD

**Issue by refaizan** [VaibhavSaini19/ResumeBuilder#1]
App is not working giving error on signup, I think app also need connection with firebase can you share templates also ?

**Comment by VaibhavSaini19** [comment]
The database and templates have been deleted and are no longer maintained. Please integrate your own firebase DB.

**Comment by refaizan** [comment]
Can you sure a template? Just want to look how you've handle the data in template.

**Comment by VaibhavSaini19** [comment]
As I said, the templates were also deleted. They were html pages containing Javascript functions called through android webview with the user Id, which would then fetch all the data about the user from the database using that Id and populate the template.

**Comment by Dhru29** [comment]
Didn't Understand solution for the same "failed to register" 

Can u please explain how to do that??

**Comment by poovarasan96** [comment]
> Can you sure a template? Just want to look how you've handle the data in template.

can you find the solution
