### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by dismilz** [VaibhavSaini19/ResumeBuilder#3]
How to add templates to my Database?
Any samples?

**Comment by VaibhavSaini19** [comment]
The templates can be stored as an html file in firebase and then fetched and displayed in a WebView. Once the page is loaded, a Javascript function call is to be made from the page which uses the user id passed to fetch the user details from firebase and populate the template html page with all the data

**Comment by dismilz** [comment]
Can I have some templates please 🥺
