### ISSUE TITLE
Firebase Storage Data is not available

### ISSUE THREAD

**Issue by aqeelzoobi** [VaibhavSaini19/ResumeBuilder#4]
I check out the project, kindly also provide the database structure of firebase database. and also provide the firebase Storage Data, so we can hit the template html files.

**Comment by honeykinng345** [comment]
hey please provide all database structures if you help others because right now this project is useless ...

**Comment by amitthakarebi** [comment]
Hey!! Please provide database storage files and Database structure.
I will donate amount.

**Comment by VaibhavSaini19** [comment]
Please check existing / closed issues (#1) before opening a new one

**Comment by pfaman** [comment]
Ok No problem
